INSERT INTO "Results" (hometeam, awayteam, hscore, ascore, winner)
VALUES ('Dinamo Zagreb', 'Ajax', 0,0, 'D'),
('Porto', 'Olympiacos', 2,2, 'D'),
('Juventus', 'Galatasaray', 2,2, 'D'),
('Athletic Club', 'Rosenborg', 1,1, 'D'),
('Sturm', 'Spartak Moscow', 0,2,'A'),
('Real Madrid', 'Inter',2,0,'H'),
('Man United', 'Barcelona', 3,3,'D'),
('Brondby', 'Bayern', 2,1,'H'),
('Panathinaikos', 'Dynamo Kyiv', 2,1,'H'),
('Lens', 'Arsenal', 1,1,'D'),
('Kaiserslautern','Benfica', 1,0,'H'),
('PSV', 'HJK', 2,1,'H'),
('Ajax','Porto',2,1,'H'),
('Spartak Moscow','Real Madrid',2,1,'H'),
('Galatasaray','Athletic Club', 2,1,'H'),
('Olympiacos','Dinamo Zagreb',2,0,'H'),
('Inter','Sturm',1,0,'H'),
('Rosenborg','Juventus',1,1,'D'),
('Bayern','Man United',2,2,'D'),
('Barcelona', 'Brondby',2,0,'H'),
('Arsenal','Panathinaikos',2,1,'H'),
('Dynamo Kyiv', 'Lens',1,1,'D'),
('HJK','Kaiserslautern',0,0,'D'),
('Benfica','PSV', 2,1,'H'),
('Porto','Dinamo Zagreb',3,0,'H'),
('Olympiacos','Ajax',1,0,'H'),
('Athletic Club','Juventus',0,0,'D'),
('Rosenborg','Galatasaray',3,0,'H'),
('Real Madrid', 'Sturm',6,1,'H'),
('Inter','Spartak Moscow',2,1,'H'),
('Brondby','Man United', 2,6,'A'),
('Bayern', 'Barcelona',1,0,'H'),
('Lens','Panathinaikos',1,0,'H'),
('Arsenal','Dynamo Kyiv',1,1,'D'),
('PSV','Kaiserslautern',1,2,'A'),
('HJK','Benfica',2,0,'H'),
('Ajax','Olympiacos',2,0,'H'),
('Spartak Moscow', 'Inter', 1,1,'D'),
('Galatasaray','Rosenborg',3,0,'H'),
('Dinamo Zagreb','Porto',3,1,'H'),
('Barcelona', 'Bayern', 1,2,'A'),
('Juventus', 'Athletic Club',1,1,'D'),
('Dynamo Kyiv','Arsenal',3,1,'H'),
('Man United','Brondby',5,0,'H'),
('Benfica','HJK',2,2,'D'),
('Panathinaikos','Lens', 1,0,'H'),
('Sturm', 'Real Madrid',1,5,'A'),
('Kaiserslautern','PSV',3,1,'H'),
('Dynamo Kyiv','Panathinaikos',2,1,'H'),
('Spartak Moscow','Sturm',0,0,'D'),
('Olympiacos','Porto',2,1,'H'),
('HJK','PSV',1,3,'A'),
('Rosenborg','Athletic Club',2,1,'H'),
('Ajax','Dinamo Zagreb',0,1,'A'),
('Bayern', 'Brondby',2,0,'H'),
('Inter','Real Madrid',3,1,'H'),
('Arsenal','Lens',0,1,'A'),
('Barcelona','Man United',3,3,'D'),
('Galatasaray', 'Juventus',1,1,'D'),
('Benfica', 'Kaiserlautern',2,1,'H'),
('Dinamo Zagreb','Olympiacos',1,1,'D'),
('Porto','Ajax',3,0,'H'),
('Juventus', 'Rosenborg',2,0,'H'),
('Athletic Club','Galatasaray',1,0,'H'),
('Sturm', 'Inter',0,2,'A'),
('Real Madrid','Spartak Moscow',2,1,'H'),
('Man United','Bayern',1,1,'D'),
('Brondby', 'Barcelona',0,2,'A'),
('Panathinaikos','Arsenal',1,3,'A'),
('Lens', 'Dynamo Kyiv',1,3,'A'),
('Kaiserlautern', 'HJK',5,2,'H'),
('PSV', 'Benfica',2,2,'D'),
('Man United', 'Inter',2,0,'H'),
('Real Madrid','Dynamo Kyiv',1,1,'D'),
('Bayern', 'Kaiserlautern',2,0,'H'),
('Juventus','Olympiacos', 2,1,'H'),
('Inter', 'Man United',1,1,'D'),
('Dynamo Kyiv','Real Madrid',2,0,'H'),
('Kaiserlautern','Bayern',0,4,'A'),
('Olympiacos','Juventus',1,1,'D'),
('Dynamo Kyiv','Bayern',3,3,'D'),
('Man United', 'Juventus',1,1,'D'),
('Bayern','Dynamo Kyiv',1,0,'H'),
('Juventus','Man United',2,3,'A'),
('Man United', 'Bayern',2,1,'H');